baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SuperSonic(0.9.10)'

[module]
  [[module.imports]]
    path = 'github.com/hugomods/baidu-analytics'

[params]
  BookTheme = 'auto'
  [params.services]
    [params.services.baidu_analytics]
      id = '21702154'